[versions]
kotlin = "1.7.10"
komapper = "1.4.0"
kotlinx-coroutines = "1.6.4"
ktor = "2.1.1"
ksp = "1.7.10-1.0.6"

[libraries]
ktor-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-callLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-defaultHeaders = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
komapper-mysql-jdbc = { module = "org.komapper:komapper-dialect-mysql-jdbc", version.ref = "komapper" }
komapper-platform = { module = "org.komapper:komapper-platform", version.ref = "komapper" }
komapper-processor = { module = "org.komapper:komapper-processor", version.ref = "komapper" }
komapper-starter-jdbc = { module = "org.komapper:komapper-starter-jdbc", version.ref = "komapper" }

[plugins]
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
